 Dataset:
     'dir' : "/mnt/data/qe_dask_benchmark_GBP"
     '2013-14' : "/mnt/data/qe_dask_benchmark_GBP/Parking_Violations_Issued_-_Fiscal_Year_2014__August_2013___June_2014_.csv"
     '2013-14_1' : "/mnt/data/qe_dask_benchmark_GBP/Parking_Violations_Issued_-_Fiscal_Year_2014__August_2013___June_2014_.csv"
     '2013-14_2' : "/mnt/data/qe_dask_benchmark_GBP/Parking_Violations_Issued_-_Fiscal_Year_2014__August_2013___June_2014_.csv"
     '2013-14_3' : "/mnt/data/qe_dask_benchmark_GBP/Parking_Violations_Issued_-_Fiscal_Year_2014__August_2013___June_2014_.csv"
     '2013-14_4' : "/mnt/data/qe_dask_benchmark_GBP/Parking_Violations_Issued_-_Fiscal_Year_2014__August_2013___June_2014_.csv"
     '2015' : "/mnt/data/qe_dask_benchmark_GBP/Parking_Violations_Issued_-_Fiscal_Year_2015.csv"
     '2015_1' : "/mnt/data/qe_dask_benchmark_GBP/Parking_Violations_Issued_-_Fiscal_Year_2015.csv"
     '2015_2' : "/mnt/data/qe_dask_benchmark_GBP/Parking_Violations_Issued_-_Fiscal_Year_2015.csv"
     '2015_3' : "/mnt/data/qe_dask_benchmark_GBP/Parking_Violations_Issued_-_Fiscal_Year_2015.csv"
     '2015_4' : "/mnt/data/qe_dask_benchmark_GBP/Parking_Violations_Issued_-_Fiscal_Year_2015.csv"
     '2016' : "/mnt/data/qe_dask_benchmark_GBP/Parking_Violations_Issued_-_Fiscal_Year_2016.csv"
     '2016_1' : "/mnt/data/qe_dask_benchmark_GBP/Parking_Violations_Issued_-_Fiscal_Year_2016.csv"
     '2016_2' : "/mnt/data/qe_dask_benchmark_GBP/Parking_Violations_Issued_-_Fiscal_Year_2016.csv"
     '2016_3' : "/mnt/data/qe_dask_benchmark_GBP/Parking_Violations_Issued_-_Fiscal_Year_2016.csv"
     '2016_4' : "/mnt/data/qe_dask_benchmark_GBP/Parking_Violations_Issued_-_Fiscal_Year_2016.csv"
     '2017' : "/mnt/data/qe_dask_benchmark_GBP/Parking_Violations_Issued_-_Fiscal_Year_2017.csv"
     '2017_1' : "/mnt/data/qe_dask_benchmark_GBP/Parking_Violations_Issued_-_Fiscal_Year_2017.csv"
     '2017_2' : "/mnt/data/qe_dask_benchmark_GBP/Parking_Violations_Issued_-_Fiscal_Year_2017.csv"
     '2017_3' : "/mnt/data/qe_dask_benchmark_GBP/Parking_Violations_Issued_-_Fiscal_Year_2017.csv"
     '2017_4' : "/mnt/data/qe_dask_benchmark_GBP/Parking_Violations_Issued_-_Fiscal_Year_2017.csv"
 clean_data:
     'dir' : "/mnt/data/qe_dask_benchmark_GBP/clean_data"
     '2013-14' : "/mnt/data/qe_dask_benchmark_GBP/clean_data/clean_data_13_14.csv"
     '2013-14_1' : "/mnt/data/qe_dask_benchmark_GBP/clean_data/clean_data_13_14_1.csv"
     '2013-14_2' : "/mnt/data/qe_dask_benchmark_GBP/clean_data/clean_data_13_14_2.csv"
     '2013-14_3' : "/mnt/data/qe_dask_benchmark_GBP/clean_data/clean_data_13_14_3.csv"
     '2013-14_4' : "/mnt/data/qe_dask_benchmark_GBP/clean_data/clean_data_13_14_4.csv"
     '2015' : "/mnt/data/qe_dask_benchmark_GBP/clean_data/clean_data_15.csv"
     '2015_1' : "/mnt/data/qe_dask_benchmark_GBP/clean_data/clean_data_15_1.csv"
     '2015_2' : "/mnt/data/qe_dask_benchmark_GBP/clean_data/clean_data_15_2.csv"
     '2015_3' : "/mnt/data/qe_dask_benchmark_GBP/clean_data/clean_data_15_3.csv"
     '2015_4' : "/mnt/data/qe_dask_benchmark_GBP/clean_data/clean_data_15_4.csv"
     '2016' : "/mnt/data/qe_dask_benchmark_GBP/clean_data/clean_data_16.csv"
     '2016_1' : "/mnt/data/qe_dask_benchmark_GBP/clean_data/clean_data_16_1.csv"
     '2016_2' : "/mnt/data/qe_dask_benchmark_GBP/clean_data/clean_data_16_2.csv"
     '2016_3' : "/mnt/data/qe_dask_benchmark_GBP/clean_data/clean_data_16_3.csv"
     '2016_4' : "/mnt/data/qe_dask_benchmark_GBP/clean_data/clean_data_16_4.csv"
     '2017' : "/mnt/data/qe_dask_benchmark_GBP/clean_data/clean_data_17.csv"
     '2017_1' : "/mnt/data/qe_dask_benchmark_GBP/clean_data/clean_data_17_1.csv"
     '2017_2' : "/mnt/data/qe_dask_benchmark_GBP/clean_data/clean_data_17_2.csv"
     '2017_3' : "/mnt/data/qe_dask_benchmark_GBP/clean_data/clean_data_17_3.csv"
     '2017_4' : "/mnt/data/qe_dask_benchmark_GBP/clean_data/clean_data_17_4.csv"
 PCA:
     'n_components' : 3
 KMeans:
     'n_clusters' : 3
     'init' : 'k-means++'
     'random_state' : 42
     'max_iter' : 1500
     'dir' : "/mnt/data/qe_dask_benchmark_GBP/kmeans"
     '2013-14' : "/mnt/data/qe_dask_benchmark_GBP/kmeans/Parking_Violations_Issued_-_Fiscal_Year_2014__August_2013___June_2014_.csv"
     '2013-14_1' : "/mnt/data/qe_dask_benchmark_GBP/kmeans/Parking_Violations_Issued_-_Fiscal_Year_2014__August_2013___June_2014_1.csv"
     '2013-14_2' : "/mnt/data/qe_dask_benchmark_GBP/kmeans/Parking_Violations_Issued_-_Fiscal_Year_2014__August_2013___June_2014_2.csv"
     '2013-14_3' : "/mnt/data/qe_dask_benchmark_GBP/kmeans/Parking_Violations_Issued_-_Fiscal_Year_2014__August_2013___June_2014_3.csv"
     '2013-14_4' : "/mnt/data/qe_dask_benchmark_GBP/kmeans/Parking_Violations_Issued_-_Fiscal_Year_2014__August_2013___June_2014_4.csv"
     '2015' : "/mnt/data/qe_dask_benchmark_GBP/kmeans/Parking_Violations_Issued_-_Fiscal_Year_2015.csv"
     '2015_1' : "/mnt/data/qe_dask_benchmark_GBP/kmeans/Parking_Violations_Issued_-_Fiscal_Year_2015_1.csv"
     '2015_2' : "/mnt/data/qe_dask_benchmark_GBP/kmeans/Parking_Violations_Issued_-_Fiscal_Year_2015_2.csv"
     '2015_3' : "/mnt/data/qe_dask_benchmark_GBP/kmeans/Parking_Violations_Issued_-_Fiscal_Year_2015_3.csv"
     '2015_4' : "/mnt/data/qe_dask_benchmark_GBP/kmeans/Parking_Violations_Issued_-_Fiscal_Year_2015_4.csv"
     '2016' : "/mnt/data/qe_dask_benchmark_GBP/kmeans/Parking_Violations_Issued_-_Fiscal_Year_2016.csv"
     '2016_1' : "/mnt/data/qe_dask_benchmark_GBP/kmeans/Parking_Violations_Issued_-_Fiscal_Year_2016_1.csv"
     '2016_2' : "/mnt/data/qe_dask_benchmark_GBP/kmeans/Parking_Violations_Issued_-_Fiscal_Year_2016_2.csv"
     '2016_3' : "/mnt/data/qe_dask_benchmark_GBP/kmeans/Parking_Violations_Issued_-_Fiscal_Year_2016_3.csv"
     '2016_4' : "/mnt/data/qe_dask_benchmark_GBP/kmeans/Parking_Violations_Issued_-_Fiscal_Year_2016_4.csv"
     '2017' : "/mnt/data/qe_dask_benchmark_GBP/kmeans/Parking_Violations_Issued_-_Fiscal_Year_2017.csv"
     '2017_1' : "/mnt/data/qe_dask_benchmark_GBP/kmeans/Parking_Violations_Issued_-_Fiscal_Year_2017_1.csv"
     '2017_2' : "/mnt/data/qe_dask_benchmark_GBP/kmeans/Parking_Violations_Issued_-_Fiscal_Year_2017_2.csv"
     '2017_3' : "/mnt/data/qe_dask_benchmark_GBP/kmeans/Parking_Violations_Issued_-_Fiscal_Year_2017_3.csv"
     '2017_4' : "/mnt/data/qe_dask_benchmark_GBP/kmeans/Parking_Violations_Issued_-_Fiscal_Year_2017_4.csv"
 artifacts : 
     'path' : '/mnt/artifacts/results'
